#!/bin/bash

THIS_SCRIPT="$0"

function node_info {
    ros2 node info $1 | fzf --bind "ctrl-a:execute($THIS_SCRIPT node_list),ctrl-e:execute($THIS_SCRIPT topic_echo {+1}),ctrl-h:execute($THIS_SCRIPT topic_hz {+1})" --preview "echo {+1} | sed 's/://' | xargs ros2 topic info -v " | awk -F: '{print $1}' | xargs $THIS_SCRIPT topic_info
}

function node_list {
    ros2 node list | fzf --bind "ctrl-a:execute($THIS_SCRIPT topic_list),ctrl-r:reload(ros2 node list)" --header 'ros2 node list:' --preview 'ros2 node info {}' | xargs $THIS_SCRIPT node_info
}

function topic_info {
    ramtmp="$(mktemp -p /dev/shm/)"

    ros2 topic info -v $1 >> $ramtmp

    perl -pe 'BEGIN{undef $/;} s/\n\n/\x0/g; s/\n$//g' $ramtmp | fzf --bind "ctrl-a:execute($THIS_SCRIPT topic_list),ctrl-e:execute($THIS_SCRIPT topic_echo $1),ctrl-h:execute($THIS_SCRIPT topic_hz $1)" --header "ros2 topic info $1:" --read0 --preview 'echo {}' | head -n 2 | awk '{print $NF}' | tac | tr '\n' '/' | tr -s '/' | sed 's/.$//' | xargs $THIS_SCRIPT node_info
    rm $ramtmp
}

function topic_list {
    ros2 topic list | fzf --bind "ctrl-a:execute($THIS_SCRIPT node_list),ctrl-r:reload(ros2 topic list),ctrl-e:execute($THIS_SCRIPT topic_echo {}),ctrl-h:execute($THIS_SCRIPT topic_hz {})" --header 'ros2 topic list:' --preview 'ros2 topic info -v {}' | xargs $THIS_SCRIPT topic_info
}

function _clean_topic_name {
    echo $1 | sed 's/://'
}

function topic_echo {
    name=$(_clean_topic_name $1)
    echo "ros2 topic echo $name" >> /dev/tty && ros2 topic echo $name >> /dev/tty
}

function topic_hz {
    name=$(_clean_topic_name $1)
    echo "ros2 topic hz $name" >> /dev/tty && ros2 topic hz $name >> /dev/tty
}

function usage {
    echo "unknown usage: $@"
}


if [ $# -lt 1 ]
then
    node_list
elif [ $# -lt 2 ]
then
    case "$1" in
    node_list) node_list ;;
    topic_list) topic_list ;;
    *) usage $@ ;;
    esac
else
    case "$1" in
    node_info) node_info $2 ;;
    topic_info) topic_info $2 ;;
    topic_echo) topic_echo $2 ;;
    topic_hz) topic_hz $2 ;;
    *) usage $@ ;;
    esac
fi


